version: '3.8'

services:
  fastapi-app:
    container_name: ${CONTAINER_NAME:-fastapi-app}
    image: ${IMAGE_NAME:-fastapi}
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - ${EXPOSED_PORT:-8000}:${UVICORN_PORT:-8000}
    command: ["python", "-m", "app.main"]
